// Localhost
###
# Get all contact information
GET http://localhost:3000/contacts
### Get individual contact info for Quinn
GET http://localhost:3000/contacts/63fa72b49da4c3d428010576
### Get individual contact info for Corinne
GET http://localhost:3000/contacts/63fa72b49da4c3d428010577
### Create PJ contact 
GET http://localhost:3000/contacts/newContact/`{"firstName":"Kickthe","lastName":"PJ","email":"PJ@gmail.com","favoriteColor":"Yellow","birthday":"August 1, 1990"}`
### Delete Katie contact
GET http://localhost:3000/contacts/deletecontact/63ff8e6f2e7c564bd3bc2fcc

// Render
### Get Home site on Render
GET https://katelyndb341.onrender.com/contacts


